sudo: true
language: julia
addons:
    apt:
        update: true
julia:
      - 1.2 
      - 1.3
after_success:
      - julia --project=. -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
